version: '3.7'

services:
  mongo:
    build:
      context: .
      dockerfile: ./images/mongo/Dockerfile
    container_name: onelab_mongo
    environment:
      MONGO_INITDB_ROOT_USERNAME: ${MONGO_ROOT_USER}
      MONGO_INITDB_ROOT_PASSWORD: ${MONGO_ROOT_PASSWORD}
      MONGO_INITDB_DATABASE: ${MONGO_INITDB_DATABASE}
      MONGO_INITDB_USERNAME: ${MONGO_USER}
      MONGO_INITDB_PASSWORD: ${MONGO_PASSWORD}
    volumes:
      - ./database:/data/db
    ports:
      - 27010:27017


