export const ACTIONS = {
  // USER
  USER_CREATE: "USER.CREATE",
  USER_UPDATE: "USER.UPDATE",
  USER_REMOVE: "USER.REMOVE",
  USER_BAN: "USER.BAN",
  USER_ACTIVATE: "USER.ACTIVATE",
  USER_DECATIVATE: "USER.DEACTIVATE",
  // SCHOOL
  SCHOOL_CREATE: "SCHOOL.CREAT",
  SCHOOL_UPDATE: "SCHOOL.UPDATE",
  SCHOOL_REMOVE: "SCHOOL.REMOVE",
  // CLASSROOM
  CLASSROOM_CREATE: "CLASSROOM.CREATE",
  CLASSROOM_UPDATE: "CLASSROOM.UPDATE",
  CLASSROOM_REMOVE: "CLASSROOM.REMOVE",
  // NOTIFICATION
  NOTIFICATION_RECEIVED: "NOTIFICATION_RECEIVED",
  NOTIFICATION_HIDE: "NOTIFICATION_HIDE",
};
